name: 'intel/publish-and-tag'
branding:
  icon: activity
  color: blue
description: 'action to publish npm package and set the same git tag to git commit'
inputs:
  npmToken:
    description: 'npm authorization token, will be added to .npmrc as is'
    required: true
  githubToken:
    description: 'github authorization token, will be used to create a tag via github api'
    required: true
  repo:
    description: '$GITHUB_REPOSITORY'
    required: true
  sha:
    description: '$GITHUB_SHA'
    required: true
  dryRun:
    description: 'flag to check version for auto publish possibility'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
